version: "3.9"
services:
  server:
    build: ./server
    ports:
    - "5000:5000"
    volumes:
    - ./server:/app
    environment:
      FLASK_ENV: development
  web:
    build: ./client/front-end
    ports:
    - "3000:3000"
    volumes:
    - ./client/front-end:/user/src/app
    depends_on:
      - server

